package com.cinemaextrem.model;
// Generated 11/06/2016 02:41:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Entrada generated by hbm2java
 */
public class Entrada  implements java.io.Serializable {


     private Integer idEnt;
     private Integer idFac;
     private Integer ubiBut;
     private BigDecimal precEnt;

    public Entrada() {
    }

    public Entrada(Integer idFac, Integer ubiBut, BigDecimal precEnt) {
       this.idFac = idFac;
       this.ubiBut = ubiBut;
       this.precEnt = precEnt;
    }
   
    public Integer getIdEnt() {
        return this.idEnt;
    }
    
    public void setIdEnt(Integer idEnt) {
        this.idEnt = idEnt;
    }
    public Integer getIdFac() {
        return this.idFac;
    }
    
    public void setIdFac(Integer idFac) {
        this.idFac = idFac;
    }
    public Integer getUbiBut() {
        return this.ubiBut;
    }
    
    public void setUbiBut(Integer ubiBut) {
        this.ubiBut = ubiBut;
    }
    public BigDecimal getPrecEnt() {
        return this.precEnt;
    }
    
    public void setPrecEnt(BigDecimal precEnt) {
        this.precEnt = precEnt;
    }




}


