package com.cinemaextrem.model;
// Generated 11/06/2016 02:41:07 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFac;
     private int idFun;
     private Date fechFac;
     private String tipFac;
     private String idCom;

    public Factura() {
    }

	
    public Factura(int idFun) {
        this.idFun = idFun;
    }
    public Factura(int idFun, Date fechFac, String tipFac, String idCom) {
       this.idFun = idFun;
       this.fechFac = fechFac;
       this.tipFac = tipFac;
       this.idCom = idCom;
    }
   
    public Integer getIdFac() {
        return this.idFac;
    }
    
    public void setIdFac(Integer idFac) {
        this.idFac = idFac;
    }
    public int getIdFun() {
        return this.idFun;
    }
    
    public void setIdFun(int idFun) {
        this.idFun = idFun;
    }
    public Date getFechFac() {
        return this.fechFac;
    }
    
    public void setFechFac(Date fechFac) {
        this.fechFac = fechFac;
    }
    public String getTipFac() {
        return this.tipFac;
    }
    
    public void setTipFac(String tipFac) {
        this.tipFac = tipFac;
    }
    public String getIdCom() {
        return this.idCom;
    }
    
    public void setIdCom(String idCom) {
        this.idCom = idCom;
    }




}


