package com.cinemaextrem.model;
// Generated 11/06/2016 02:41:07 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Funcion generated by hbm2java
 */
public class Funcion  implements java.io.Serializable {


     private Integer idFun;
     private Pelicula pelicula;
     private Sala sala;
     private String dimPel;
     private String idiomaPel;
     private Date fecFunI;
     private Date fecFunF;

    public Funcion() {
    }

    public Funcion(Pelicula pelicula, Sala sala, String dimPel, String idiomaPel, Date fecFunI, Date fecFunF) {
       this.pelicula = pelicula;
       this.sala = sala;
       this.dimPel = dimPel;
       this.idiomaPel = idiomaPel;
       this.fecFunI = fecFunI;
       this.fecFunF = fecFunF;
    }
   
    public Integer getIdFun() {
        return this.idFun;
    }
    
    public void setIdFun(Integer idFun) {
        this.idFun = idFun;
    }
    public Pelicula getPelicula() {
        return this.pelicula;
    }
    
    public void setPelicula(Pelicula pelicula) {
        this.pelicula = pelicula;
    }
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }
    public String getDimPel() {
        return this.dimPel;
    }
    
    public void setDimPel(String dimPel) {
        this.dimPel = dimPel;
    }
    public String getIdiomaPel() {
        return this.idiomaPel;
    }
    
    public void setIdiomaPel(String idiomaPel) {
        this.idiomaPel = idiomaPel;
    }
    public Date getFecFunI() {
        return this.fecFunI;
    }
    
    public void setFecFunI(Date fecFunI) {
        this.fecFunI = fecFunI;
    }
    public Date getFecFunF() {
        return this.fecFunF;
    }
    
    public void setFecFunF(Date fecFunF) {
        this.fecFunF = fecFunF;
    }




}


