package com.cinemaextrem.model;
// Generated 11/06/2016 02:41:07 by Hibernate Tools 4.3.1



/**
 * Pcanje generated by hbm2java
 */
public class Pcanje  implements java.io.Serializable {


     private Integer idPcan;
     private String descPcan;
     private Integer puntPcan;

    public Pcanje() {
    }

    public Pcanje(String descPcan, Integer puntPcan) {
       this.descPcan = descPcan;
       this.puntPcan = puntPcan;
    }
   
    public Integer getIdPcan() {
        return this.idPcan;
    }
    
    public void setIdPcan(Integer idPcan) {
        this.idPcan = idPcan;
    }
    public String getDescPcan() {
        return this.descPcan;
    }
    
    public void setDescPcan(String descPcan) {
        this.descPcan = descPcan;
    }
    public Integer getPuntPcan() {
        return this.puntPcan;
    }
    
    public void setPuntPcan(Integer puntPcan) {
        this.puntPcan = puntPcan;
    }




}


