package com.cinemaextrem.model;
// Generated 11/06/2016 02:41:07 by Hibernate Tools 4.3.1



/**
 * Pelipuntos generated by hbm2java
 */
public class Pelipuntos  implements java.io.Serializable {


     private Integer idPp;
     private Integer idPel;
     private Integer idUsr;
     private Integer puntaje;

    public Pelipuntos() {
    }

    public Pelipuntos(Integer idPel, Integer idUsr, Integer puntaje) {
       this.idPel = idPel;
       this.idUsr = idUsr;
       this.puntaje = puntaje;
    }
   
    public Integer getIdPp() {
        return this.idPp;
    }
    
    public void setIdPp(Integer idPp) {
        this.idPp = idPp;
    }
    public Integer getIdPel() {
        return this.idPel;
    }
    
    public void setIdPel(Integer idPel) {
        this.idPel = idPel;
    }
    public Integer getIdUsr() {
        return this.idUsr;
    }
    
    public void setIdUsr(Integer idUsr) {
        this.idUsr = idUsr;
    }
    public Integer getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(Integer puntaje) {
        this.puntaje = puntaje;
    }




}


