package com.cinemaextrem.model;
// Generated 11/06/2016 02:41:07 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pelicoment generated by hbm2java
 */
public class Pelicoment  implements java.io.Serializable {


     private Integer idcoment;
     private Integer idPel;
     private Integer idUsr;
     private String comentario;
     private Date fechComent;

    public Pelicoment() {
    }

    public Pelicoment(Integer idPel, Integer idUsr, String comentario, Date fechComent) {
       this.idPel = idPel;
       this.idUsr = idUsr;
       this.comentario = comentario;
       this.fechComent = fechComent;
    }
   
    public Integer getIdcoment() {
        return this.idcoment;
    }
    
    public void setIdcoment(Integer idcoment) {
        this.idcoment = idcoment;
    }
    public Integer getIdPel() {
        return this.idPel;
    }
    
    public void setIdPel(Integer idPel) {
        this.idPel = idPel;
    }
    public Integer getIdUsr() {
        return this.idUsr;
    }
    
    public void setIdUsr(Integer idUsr) {
        this.idUsr = idUsr;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Date getFechComent() {
        return this.fechComent;
    }
    
    public void setFechComent(Date fechComent) {
        this.fechComent = fechComent;
    }




}


