package com.cinemaextrem.model;
// Generated 11/06/2016 02:41:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Precios generated by hbm2java
 */
public class Precios  implements java.io.Serializable {


     private Integer idPrec;
     private String dimPel;
     private String desPrec;
     private BigDecimal montPres;

    public Precios() {
    }

    public Precios(String dimPel, String desPrec, BigDecimal montPres) {
       this.dimPel = dimPel;
       this.desPrec = desPrec;
       this.montPres = montPres;
    }
   
    public Integer getIdPrec() {
        return this.idPrec;
    }
    
    public void setIdPrec(Integer idPrec) {
        this.idPrec = idPrec;
    }
    public String getDimPel() {
        return this.dimPel;
    }
    
    public void setDimPel(String dimPel) {
        this.dimPel = dimPel;
    }
    public String getDesPrec() {
        return this.desPrec;
    }
    
    public void setDesPrec(String desPrec) {
        this.desPrec = desPrec;
    }
    public BigDecimal getMontPres() {
        return this.montPres;
    }
    
    public void setMontPres(BigDecimal montPres) {
        this.montPres = montPres;
    }




}


