package com.cinemaextrem.model;
// Generated 11/06/2016 02:41:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private int nroSala;
     private Integer capacidadS;
     private String tipoDeProy;
     private Set<Funcion> funcions = new HashSet<Funcion>(0);

    public Sala() {
    }

	
    public Sala(int nroSala) {
        this.nroSala = nroSala;
    }
    public Sala(int nroSala, Integer capacidadS, String tipoDeProy, Set<Funcion> funcions) {
       this.nroSala = nroSala;
       this.capacidadS = capacidadS;
       this.tipoDeProy = tipoDeProy;
       this.funcions = funcions;
    }
   
    public int getNroSala() {
        return this.nroSala;
    }
    
    public void setNroSala(int nroSala) {
        this.nroSala = nroSala;
    }
    public Integer getCapacidadS() {
        return this.capacidadS;
    }
    
    public void setCapacidadS(Integer capacidadS) {
        this.capacidadS = capacidadS;
    }
    public String getTipoDeProy() {
        return this.tipoDeProy;
    }
    
    public void setTipoDeProy(String tipoDeProy) {
        this.tipoDeProy = tipoDeProy;
    }
    public Set<Funcion> getFuncions() {
        return this.funcions;
    }
    
    public void setFuncions(Set<Funcion> funcions) {
        this.funcions = funcions;
    }



}


